export const MOCK_LIST = [
  {
    id: 400,
    faction: "Norwinger",
    unitName: "Gar'worgar",
    rangedWeapon: "x",
    rangedAttackStats: "0",
    uniqueUnit: false,
    leader: false,
    standardBearer: false,
    musician: false,
    unitType: "G",
    wedgeFormation: false,
    skirmishFormation: false,
    squareFormation: false,
    horde: false,
    commandStars: 0,
    magic: 0,
    subFaction: "Mächtige Wesen",
    points: 160,
    numberOfElements: 1,
    move: 20,
    charge: 16,
    skirmish: 10,
    hold_maneuvers: 6,
    controlZone_OverRun: 8,
    initiative: 2,
    unitSize: 5,
    armourRange: 3,
    armourMelee: 6,
    weapon1: 12,
    weapon2: 12,
    skillMelee: 0,
    skillRange: 0,
    fear: 3,
    moral1: 0,
    moral2: 10,
    hitpoints: 5,
    specialRules: "FK-Pz 6, NK-Pz 9 vorderes Feld, Gehorsamstests mit +1/-1, Wald 4 BP",
    name: "Gar'worgar",
    uniqueID: "c83b1dec-2b87-44f4-86d8-6ffb86697ef8",
    equipment: [],
    equipmentTypes: {
      poison: false,
      warpaint: false,
      maxMagic: 1,
    },
  },

  {
    id: 419,
    faction: "Norwinger",
    unitName: "Shae",
    rangedWeapon: "x",
    rangedAttackStats: "0",
    uniqueUnit: false,
    leader: false,
    standardBearer: false,
    musician: false,
    unitType: "M",
    wedgeFormation: false,
    skirmishFormation: false,
    squareFormation: false,
    horde: false,
    commandStars: 0,
    magic: 1,
    subFaction: "Hexe",
    points: 170,
    numberOfElements: 1,
    move: 24,
    charge: 24,
    skirmish: 24,
    hold_maneuvers: 24,
    controlZone_OverRun: 0,
    initiative: 2,
    unitSize: 2,
    armourRange: 1,
    armourMelee: 3,
    weapon1: 8,
    weapon2: 0,
    skillMelee: 1,
    skillRange: 0,
    fear: 1,
    moral1: 0,
    moral2: 0,
    hitpoints: 2,
    specialRules: "Keule, +1 gg Eishexen",
    name: "Shae",
    uniqueID: "c5625d1f-e280-4b99-b807-9ccef5785165",
    equipment: [
      {
        name: "Das Dornenschild",
        type: "armor",
        rule: "Es erlaubt dem Träger einmal pro Runde in einer beliebigen Fernkampfphase einen Fernkampf mit 6 Felder KF 7 durchzuführen.\r\n\r\nSollte das Element einen eigenen Fernkampfangriff haben, muss sich der Spieler entscheiden, ob er mit seiner regul?ren Bewaffnung oder mit dem Dornenschild fernk?mpfen m?chte. Sollte das Element über eine Fernkampffertigkeiten verfügen wird diese zum Angriff hinzugerechnet.",
        points: 30,
      },
      {
        name: "Heiltrank",
        type: "potion",
        rule: "regeneriert einmal 2 TP, beliebig, vor oder nach NK-phase, generisch",
        points: 40,
      },
      {
        name: "Das Dornenschild",
        type: "armor",
        rule: "Es erlaubt dem Träger einmal pro Runde in einer beliebigen Fernkampfphase einen Fernkampf mit 6 Felder KF 7 durchzuführen.\r\n\r\nSollte das Element einen eigenen Fernkampfangriff haben, muss sich der Spieler entscheiden, ob er mit seiner regul?ren Bewaffnung oder mit dem Dornenschild fernk?mpfen m?chte. Sollte das Element über eine Fernkampffertigkeiten verfügen wird diese zum Angriff hinzugerechnet.",
        points: 30,
      },
      {
        name: "Heiltrank",
        type: "potion",
        rule: "regeneriert einmal 2 TP, beliebig, vor oder nach NK-phase, generisch",
        points: 40,
      },
      {
        name: "Das Dornenschild",
        type: "armor",
        rule: "Es erlaubt dem Träger einmal pro Runde in einer beliebigen Fernkampfphase einen Fernkampf mit 6 Felder KF 7 durchzuführen.\r\n\r\nSollte das Element einen eigenen Fernkampfangriff haben, muss sich der Spieler entscheiden, ob er mit seiner regul?ren Bewaffnung oder mit dem Dornenschild fernk?mpfen m?chte. Sollte das Element über eine Fernkampffertigkeiten verfügen wird diese zum Angriff hinzugerechnet.",
        points: 30,
      },
      {
        name: "Heiltrank",
        type: "potion",
        rule: "regeneriert einmal 2 TP, beliebig, vor oder nach NK-phase, generisch",
        points: 40,
      },
      
    ],
    equipmentTypes: {
      poison: false,
      warpaint: false,
      maxMagic: 1,
      potion: false,
    },
  },

  {
    id: 385,
    faction: "Norwinger",
    unitName: "Schnee-Oger",
    rangedWeapon: "x",
    rangedAttackStats: "0",
    uniqueUnit: false,
    leader: true,
    standardBearer: false,
    musician: false,
    unitType: "I",
    wedgeFormation: false,
    skirmishFormation: false,
    squareFormation: false,
    horde: false,
    commandStars: 0,
    magic: 0,
    subFaction: "Barbaren",
    points: 130,
    numberOfElements: 8,
    move: 24,
    charge: 18,
    skirmish: 12,
    hold_maneuvers: 1,
    controlZone_OverRun: 0,
    initiative: 2,
    unitSize: 3,
    armourRange: 0,
    armourMelee: 2,
    weapon1: 12,
    weapon2: 0,
    skillMelee: 0,
    skillRange: 0,
    fear: 1,
    moral1: 6,
    moral2: 14,
    hitpoints: 1,
    specialRules: "Zweihandwaffe, Eis!",
    name: "Schnee-Oger",
    uniqueID: "3cd11b4f-f6a8-4d1b-91ec-e85a6c69da6e",
    equipment: [
      {
        name: "Dunkelbier",
        type: "item",
        rule: "Infanterieeinheiten der Goblins, der Norwinger, der Thainer und der Zwerge\r\n\r\nDie Einheit erh?lt für den Rest des Spieles einen Bonus von +4 Bewegungspunkten in jedem Befehl und eine Erh?hung der Kampfkraft von +2 auf alle mitgeführten Nahkampfwaffen.\r\n\r\nLeider sinkt aufgrund des Rausches die Koordination der Einheit: Zum einen kann die Einheit selbst, eine entsprechende Bewaffnung vorausgesetzt, einen Fernkampf nur mit einem um 1 verringerten Kampffaktor ausführen, des Weiteren k?mpfen alle Nahkampfgegner gegen Einheiten unter Einfluss von Dunkelbier mit einem um 1 erhöhten Nahkampffaktor.",
        points: 20,
      },
    ],
    equipmentTypes: {
      poison: false,
      warpaint: false,
      maxMagic: 1,
    },
  },
];
