import {
  DARKELF_TEXTS,
  DWARF_TEXTS,
  EMPIRE_TEXTS,
  GOBLIN_TEXTS,
  ISTHAK_TEXTS,
  LIZARDMEN_TEXTS,
  NORWINGER_TEXTS,
  SOUTHERN_CITY_STATES_TEXTS,
  SPECIAL_TEXTS,
  THAIN_TEXTS,
  UNDEAD_TEXTS,
  ELF_TEXTS,
  ORK_CLANS_TEXTS,
  ORKS_OF_CLANNGETT_TEXTS,
} from "./textsAndMessages";

// SINGLE FACTIONS
export const DARKELVES = DARKELF_TEXTS.FACTION_NAME;
export const DWARVES = DWARF_TEXTS.FACTION_NAME;
export const ELVES = ELF_TEXTS.FACTION_NAME;
export const EMPIRE = EMPIRE_TEXTS.FACTION_NAME;
export const GOBLINS = GOBLIN_TEXTS.FACTION_NAME;
export const ISTHAK = ISTHAK_TEXTS.FACTION_NAME;
export const LIZARDKIN = LIZARDMEN_TEXTS.FACTION_NAME;
export const NORWINGER = NORWINGER_TEXTS.FACTION_NAME;
export const ORK_CLANS = ORK_CLANS_TEXTS.FACTION_NAME;
export const ORKS_OF_CLANNGETT = ORKS_OF_CLANNGETT_TEXTS.FACTION_NAME;
export const SOUTHERN_CITY_STATES = SOUTHERN_CITY_STATES_TEXTS.FACTION_NAME;
export const SPECIAL = SPECIAL_TEXTS.FACTION_NAME;
export const THAIN = THAIN_TEXTS.FACTION_NAME;
export const UNDEAD = UNDEAD_TEXTS.FACTION_NAME;

// SPECIAL INDICATORS
export const NONE = "NONE";
export const NO_ALLY = "NO_ALLY";

// ALL FACTIONS
export const ALL_FACTIONS_ARRAY = [
  DARKELVES,
  DWARVES,
  ELVES,
  GOBLINS,
  LIZARDKIN,
  EMPIRE,
  ISTHAK,
  NORWINGER,
  ORK_CLANS,
  ORKS_OF_CLANNGETT,
  SOUTHERN_CITY_STATES,
  THAIN,
  UNDEAD,
];

export const ALTERNATIVE_ARMY_SELECTION_TEXT = {
  [DWARVES]: [
    DWARF_TEXTS.SELECTION_TEXTS.FOURTY_PERCENT, //
    DWARF_TEXTS.SELECTION_TEXTS.TWENTY_PERCENT,
  ],
  [EMPIRE]: [
    EMPIRE_TEXTS.FIRST_SELECTION_TEXT, //
    EMPIRE_TEXTS.SECOND_SELECTION_TEXT,
  ],
  [ORK_CLANS]: [
    ORK_CLANS_TEXTS.CLAN_SELECTION.FIRST_SELECTION_TEXT, //
    ORK_CLANS_TEXTS.CLAN_SELECTION.SECOND_SELECTION_TEXT,
  ],
};

export const ARMIES_TWO_CHOICES_PER_ALTERNATIVE_LIST = [DWARVES];

 