import {
  DWARF_TEXTS, //
  EMPIRE_TEXTS,
  SPECIAL_TEXTS,
  ORK_CLANS_TEXTS,
} from "./textsAndMessages";

// SINGLE FACTIONS
export const DWARVES = DWARF_TEXTS.FACTION_NAME;
export const SPECIAL = SPECIAL_TEXTS.FACTION_NAME;
export const EMPIRE = EMPIRE_TEXTS.FACTION_NAME;
export const ORK_CLANS = ORK_CLANS_TEXTS.FACTION_NAME;

// SPECIAL INDICATORS
export const NONE = "NONE";
export const NO_ALLY = "NO_ALLY";

export const ALTERNATIVE_ARMY_SELECTION_TEXT = {
  [DWARVES]: [
    DWARF_TEXTS.SELECTION_TEXTS.FOURTY_PERCENT, //
    DWARF_TEXTS.SELECTION_TEXTS.TWENTY_PERCENT,
  ],
  [EMPIRE]: [
    EMPIRE_TEXTS.FIRST_SELECTION_TEXT, //
    EMPIRE_TEXTS.SECOND_SELECTION_TEXT,
  ],
  [ORK_CLANS]: [
    ORK_CLANS_TEXTS.CLAN_SELECTION.FIRST_SELECTION_TEXT, //
    ORK_CLANS_TEXTS.CLAN_SELECTION.SECOND_SELECTION_TEXT,
  ],
};

export const ARMIES_TWO_CHOICES_PER_ALTERNATIVE_LIST = [DWARVES];
