// react-pdf
import { Text, View, Image } from "@react-pdf/renderer";
// detailedStyles
import { detailedStyles } from "../../../components/PDFGenerator/pdfStyles/detailedCardPdfStyles";
// components and functions
import { setUnitStat } from "../../../gameLogic/unitStatChangeLogic/unitStatChangesLogic";

/**
 * PDF component to be used w. the react-pdf libary. Renders a unit stat as an icon for the army list pdf generated by the app.
 * The icon consists of a custom icon followed by the
 * numerical value of the stat.
 * E.g.: a shield Icon icon followed by the range armor stat.
 * PLEASE NOTE: the component renders the stat dynamically. If the
 * numerical value of stat changes due to item bonuses,
 * the component re-renders.
 * @param {object} props
 * @returns a JSX element.
 */
const PdfStatCardIcon = (props) => {
  const iconValueStyle = detailedStyles.iconValueGroup;
  const iconStyle = detailedStyles.icon;

  const stat = setUnitStat(props.unit, props.stat);

  return props.display ? (
    <View style={iconValueStyle}>
      <Image src={props.icon} style={iconStyle} />
      <Text>{stat}</Text>
    </View>
  ) : null;
};

export default PdfStatCardIcon;
