import { COMPENDIUM, CARD_TEXT } from "../../../../constants/textsAndMessages";

/**
 * Since the state for the compendium table is relatively large, it is put in its own file
 */

export const CompendiumTableStateArray = [
  // button
  {
    toggleGroup: "button",
    displayGroup: true,
    columns: [
      {
        column: "lock",
        label: COMPENDIUM.LOCK,
        displayed: true,
        type: "button",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },

      {
        column: "cardViewButton",
        label: COMPENDIUM.CARD_BUTTON,
        displayed: true,
        type: "button",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  //   "naming"
  {
    toggleGroup: "naming",
    displayGroup: true,
    columns: [
      {
        column: "faction",
        label: COMPENDIUM.FACTION,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "20px",
        maxColumnWidth: "130px",
      },
      {
        column: "subFaction",
        label: COMPENDIUM.SUBFACTION,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "unitName",
        label: COMPENDIUM.NAME,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "50px",
        maxColumnWidth: "130px",
      },
    ],
  },
  // unitCharacteristics
  {
    toggleGroup: "unitCharacteristics",
    displayGroup: true,
    columns: [
      {
        column: "unitType",
        label: COMPENDIUM.UNITTYPE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "numberOfElements",
        label: CARD_TEXT.ELEMENTS,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "1px",
        maxColumnWidth: "130px",
      },
      {
        column: "standardBearer",
        label: COMPENDIUM.STANDARDBEARER,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "musician",
        label: COMPENDIUM.MUSICIAN,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "wedgeFormation",
        label: COMPENDIUM.WEDGEFORMATION,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "skirmishFormation",
        label: COMPENDIUM.SKIRMISHFORMATION,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "squareFormation",
        label: COMPENDIUM.SQUAREFORMATION,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "horde",
        label: COMPENDIUM.HORDE,
        displayed: true,
        type: "boolean",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // movement
  {
    toggleGroup: "movementGroup",
    displayGroup: true,
    columns: [
      {
        column: "move",
        label: COMPENDIUM.MOVE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "charge",
        label: COMPENDIUM.CHARGE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "skirmish",
        label: COMPENDIUM.SKIRMISH,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "hold_maneuvers",
        label: COMPENDIUM.HOLD_MANEUVERS,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // defenseGroup
  {
    toggleGroup: "defenseGroup",
    displayGroup: true,
    columns: [
      {
        column: "unitSize",
        label: COMPENDIUM.UNIT_SIZE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "armourRange",
        label: COMPENDIUM.ARMOURRANGE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "armourMelee",
        label: COMPENDIUM.ARMOURMELEE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // defenseGroup
  {
    toggleGroup: "defenseGroup",
    displayGroup: true,
    columns: [
      {
        column: "weapon1",
        label: COMPENDIUM.WEAPON1,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "weapon2",
        label: COMPENDIUM.WEAPON2,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "weapon3",
        label: COMPENDIUM.WEAPON3,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "rangedWeapon",
        label: COMPENDIUM.RANGEDWEAPON,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "skillMelee",
        label: COMPENDIUM.SKILLMELEE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "skillRange",
        label: COMPENDIUM.SKILLRANGE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "initiative",
        label: COMPENDIUM.INITIATIVE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // heroCharacteristicsGroup
  {
    toggleGroup: "heroCharacteristicsGroup",
    displayGroup: true,
    columns: [
      {
        column: "commandStars",
        label: COMPENDIUM.COMMANDSTARS,
        displayed: true,
        type: "command",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "magic",
        label: COMPENDIUM.MAGIC,
        displayed: true,
        type: "magic",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "controlZone",
        label: COMPENDIUM.CONTROLZONE,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "1px",
        maxColumnWidth: "130px",
      },
      {
        column: "OverRun",
        label: COMPENDIUM.OVERRUN,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // toughnessGroup
  {
    toggleGroup: "toughnessGroup",
    displayGroup: true,
    columns: [
      {
        column: "hitpoints",
        label: COMPENDIUM.HITPOINTS,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "fear",
        label: COMPENDIUM.FEAR,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "moral1",
        label: COMPENDIUM.MORAL1,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "moral2",
        label: COMPENDIUM.MORAL2,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
  // rulesPointsGroup
  {
    toggleGroup: "rulesPointsGroup",
    displayGroup: true,
    columns: [
      {
        column: "specialRules",
        label: COMPENDIUM.SPECIALRULES,
        displayed: true,
        type: "specialRules",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "points",
        label: COMPENDIUM.POINTS,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "effectiveness_1",
        label: COMPENDIUM.EFFECTIVENESS_1,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
      {
        column: "effectiveness_2",
        label: COMPENDIUM.EFFECTIVENESS_2,
        displayed: true,
        type: "text",
        minColumnWidth: "5px",
        columnWidth: "2em",
        maxColumnWidth: "130px",
      },
    ],
  },
];
